apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-app        # Must match pipeline kubectl rollout status
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-app
  template:
    metadata:
      labels:
        app: student-app
    spec:
      # Init container waits for MySQL to be ready
      initContainers:
        - name: wait-for-mysql
          image: busybox
          command: ['sh', '-c', 'until nc -z mysql-service 3306; do echo waiting for mysql; sleep 2; done']
      containers:
        - name: student-app
          image: student-app:latest   # Must match Docker build in pipeline
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: student-app-service
spec:
  selector:
    app: student-app
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
